                                                           NumPy Mastery Roadmap                                                

Introduction:
NumPy (Numerical Python) is a powerful open-source library for numerical computing in Python. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these structures efficiently. NumPy is widely used in scientific computing, data analysis, artificial intelligence, and machine learning, making it an essential tool for researchers, engineers, and developers.

1.How to install the Numpy 

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.2 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


2.Basic NumPy Operations
  * Creating NumPy Arrays

In [2]:
import numpy as np
# Creating a 1D array
arr1d = np.array([1, 2, 3, 4, 5])
print(arr1d)

# Creating a 2D array
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2d)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


 Checking Array Properties

In [3]:
print(arr1d.shape)  # (5,)
print(arr2d.shape)  # (2,3)
print(arr1d.dtype)  # int32 or int64 depending on the system
print(arr2d.dtype)  # int32 or int64 depending on the system
print(arr1d.ndim)   # Number of dimensions 1
print(arr2d.ndim)   # Number of dimensions  2

(5,)
(2, 3)
int32
int32
1
2


Special Arrays
  * Zeros Array
  * Ones Array
  * Identity Matrix
  * Random Array

In [4]:
#zero array
print(np.zeros((3,3))) #Creates a 3×3 matrix filled with zeros
                       #Used as a placeholder or initialization for matrices when no values are available yet.

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
#ones array
print(np.ones((2,3)))#Creates a 2×3 matrix filled with ones.
                     #Often used for initializing weights in neural networks or for mathematical operations.

[[1. 1. 1.]
 [1. 1. 1.]]


In [6]:
#Identity Matrix
print(np.eye(3)) #Creates a 3×3 identity matrix (diagonal elements are 1, rest are 0).
                 #Identity matrices are useful in linear algebra, matrix transformations, and neural network computations.


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


3. Array Operations
   * Addition
   * Subtraction
   * Multiplication
   * Division 
   * Power 
   * Modulo
   * Matrix Multiplication

In [7]:
# Addition
import numpy as np

arr = np.array([1, 2, 3, 4])
print(arr + 2)  # Adds 2 to each element[3 4 5 6]

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(arr1 + arr2)  # Element-wise addition[5 7 9]

[3 4 5 6]
[5 7 9]


In [8]:
#Subtraction
import numpy as np

arr = np.array([1, 2, 3, 4])
print(arr - 1)  # subtract 2 to each element[0 1 2 3]

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(arr2-arr1)  # Element-wise subtract[3 3 3]

[0 1 2 3]
[3 3 3]


In [9]:
#Multiplication
import numpy as np

arr = np.array([1, 2, 3, 4])
print(arr * 2)  # Multiply 2 to each element[2 4 6 8]

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(arr2 * arr1)  # Element-wise multiply[4 10 18]

[2 4 6 8]
[ 4 10 18]


In [10]:
#Division
import numpy as np

arr = np.array([2, 4, 6, 8])
print(arr / 2)  # divided by 2 to each element[1. 2. 3. 4.]

arr1 = np.array([16, 25, 35])
arr2 = np.array([4, 5, 6])
print(arr1 / arr2)  # Element-wise divided[4. 5. 5.83333333]

[1. 2. 3. 4.]
[4.         5.         5.83333333]


In [11]:
#power
A = np.array([2, 4, 6, 8])
print(A ** 2)  # Square of each element


[ 4 16 36 64]


In [12]:
#Modulo
A = np.array([2, 4, 6, 8])
print(A % 3) #Computes remainder for each element.


[2 1 0 2]


In [13]:
#Matrix Multiplication
A = np.array([[1, 2], [3, 4]])      
B = np.array([[5, 6], [7, 8]])
print(np.dot(A, B))   #This performs actual matrix multiplication, not element-wise multiplication

[[19 22]
 [43 50]]


4. Indexing and Slicing
   * 1D Array Indexing
   * 2D Array Indexing
   * Boolean Indexing
   * Slicing formula
   * 1D Array Slicing
   * 2D Array Slicing

In [14]:
# 1d array indexing
import numpy as np
arr = np.array([10, 20, 30, 40, 50])

print(arr[0])   # First element (index 0)(10)
print(arr[2])   # Third element (index 2)(30)
print(arr[-1])  # Last element (negative index)(50)


10
30
50


In [15]:
# 2d array indexing
mat = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(mat[0, 0])  # First row, first column (1)
print(mat[1, 2])  # Second row, third column (6)
print(mat[-1, -1])  # Last row, last column (9)


1
6
9


In [20]:
#Boolean Indexing
arr = np.array([10, 20, 30, 40, 50])

print(arr[arr > 25])  # Get values greater than 25
print(arr[arr % 20 == 0])  # Get values divisible by 20


[30 40 50]
[20 40]


Slicing Formula
 * array[start:stop:step]
 * start: Where slicing begins (inclusive)
 * stop: Where slicing stops (exclusive)
 * step: Interval between elements 

In [18]:
#1D Array Slicing
arr = np.array([10, 20, 30, 40, 50, 60])

print(arr[1:4])   # Elements from index 1 to 3
print(arr[:3])    # First three elements
print(arr[2:])    # Elements from index 2 to end
print(arr[::2])   # Every second element
print(arr[::-1])  # Reverse the array
print(arr[0:5:2])
print(arr[0:len(arr)])

[20 30 40]
[10 20 30]
[30 40 50 60]
[10 30 50]
[60 50 40 30 20 10]
[10 30 50]
[10 20 30 40 50 60]


In [19]:
#2D array slicing
mat = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])

print(mat[:2, :2])  # Top-left 2×2 submatrix
print(mat[1:, 1:])  # Bottom-right 2×2 submatrix
print(mat[:, 1])    # Second column (all rows)
print(mat[1, :])    # Second row (all columns)


[[1 2]
 [4 5]]
[[5 6]
 [8 9]]
[2 5 8]
[4 5 6]


5. Reshaping and Manipulating Arrays

In [21]:
arr = np.arange(9)  # Creates an array from 0 to 8
reshaped_arr = arr.reshape((3, 3))  # Reshape to 3x3 matrix
print(reshaped_arr)

# Flattening an array
flattened = reshaped_arr.flatten()
print(flattened)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2 3 4 5 6 7 8]


6. Statistical and Mathematical Functions
   * Mean
   * Median
   * Standard deviation
   * Sum of elements
   * Minimum and maximum

In [23]:
import numpy as np

arr = np.array([1,2,3,4,5]) # 1D array

print(np.mean(arr))  # Mean: (sum of all elements) / (total number of elements)
print(np.median(arr))  # Median: Middle value when elements are sorted
print(np.std(arr))  # Standard Deviation: sqrt(mean((x - mean)^2))
print(np.sum(arr))  # Sum: Total of all elements
print(np.min(arr), np.max(arr))  # Minimum and Maximum values in the array


3.0
3.0
1.4142135623730951
15
1 5


In [24]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]]) # 2D array 

print(np.mean(arr))  # Mean: (sum of all elements) / (total number of elements)
print(np.median(arr))  # Median: Middle value when elements are sorted
print(np.std(arr))  # Standard Deviation: sqrt(mean((x - mean)^2))
print(np.sum(arr))  # Sum: Total of all elements
print(np.min(arr), np.max(arr))  # Minimum and Maximum values in the array


3.5
3.5
1.707825127659933
21
1 6


7.Broadcasting
  * What is Broadcasting
    * Broadcasting allows NumPy to perform operations between arrays of different shapes without explicitly reshaping them. It automatically expands smaller arrays to match the shape of larger ones during arithmetic operations

In [25]:
import numpy as np

arr = np.array([[1, 2, 3], 
                [4, 5, 6]])

b = np.array([10, 20, 30])  # 1D array

result = arr + b  # Broadcasting: b is expanded across rows
print(result)


[[11 22 33]
 [14 25 36]]


In [26]:
arr = np.array([[1, 2, 3], 
                [4, 5, 6]])

print(np.sum(arr, axis=0))  # Sum along columns
print(np.sum(arr, axis=1))  # Sum along rows


[5 7 9]
[ 6 15]


In [27]:
arr = np.array([[1, 2, 3], 
                [4, 5, 6]])

print(arr + 10)  # Broadcasting a scalar


[[11 12 13]
 [14 15 16]]


8.Matrix Operations in NumPy
  * Matrix Multiplication
  * Matrix Inverse
  * Determinant

In [28]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Matrix multiplication
print(np.dot(A, B))


[[19 22]
 [43 50]]


In [29]:
#Matrix inverse
A = np.array([[1, 2], [3, 4]])
print(np.linalg.inv(A))


[[-2.   1. ]
 [ 1.5 -0.5]]


In [30]:
# Determinant
A = np.array([[1, 2], [3, 4]])
print(np.linalg.det(A))


-2.0000000000000004


9. Working with Missing Data

In [31]:
arr = np.array([1, 2, np.nan, 4, 5])
print(np.isnan(arr))  # Identifying NaN values
print(np.nanmean(arr))  # Mean ignoring NaN values

[False False  True False False]
3.0


10. Saving and Loading Data

In [32]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
np.save('array.npy', arr)  # Save as .npy file
loaded_arr = np.load('array.npy')  # Load the file
print(loaded_arr)

[[1 2 3]
 [4 5 6]]
